# Generated by Django 4.1.7 on 2023-10-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_design_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='term',
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('courses', models.ManyToManyField(related_name='terms', to='course_design_app.course')),
            ],
        ),
    ]
