# Generated by Django 4.1.7 on 2023-10-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_design_app', '0004_remove_course_term_term'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='courses',
        ),
        migrations.AlterField(
            model_name='term',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
