# Generated by Django 4.1.7 on 2023-11-01 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_design_app', '0006_term_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='courses',
        ),
        migrations.AddField(
            model_name='course',
            name='credits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='grade',
            field=models.CharField(default='A', max_length=2),
        ),
        migrations.AddField(
            model_name='course',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='term',
            name='gpa',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='term',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='term',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
