# Generated by Django 4.1.7 on 2023-11-13 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_design_app', '0007_remove_term_courses_course_credits_course_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='credits',
        ),
        migrations.RemoveField(
            model_name='course',
            name='user',
        ),
        migrations.RemoveField(
            model_name='term',
            name='gpa',
        ),
        migrations.RemoveField(
            model_name='term',
            name='user',
        ),
        migrations.AddField(
            model_name='course',
            name='term',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course_design_app.term'),
        ),
        migrations.AlterField(
            model_name='course',
            name='grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='term',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
